vars:
    - data: "../../data/"
    - models: "../../models/"
    - results: "../../results"
    - grants_tagger: "../../grants_tagger/"
stages:
    preprocess_wellcome_science:
      cmd: grants_tagger preprocess wellcome-science ${data}/raw/science_tags_full_version.xlsx
        ${data}/processed/science_grants_tagged_title_synopsis.jsonl ${models}/label_binarizer.pkl
      deps:
        - ${data}/raw/science_tags_full_version.xlsx
        - ${grants_tagger}/preprocess_wellcome.py
      params:
        - preprocess_wellcome_science.text_cols
        - preprocess_wellcome_science.meta_cols
      outs:
        - ${data}/processed/science_grants_tagged_title_synopsis.jsonl
        - ${models}/label_binarizer.pkl
    train_tfidf_svm:
      cmd: grants_tagger train ${data}/processed/science_grants_tagged_title_synopsis.jsonl
        ${models}/label_binarizer.pkl ${models}/tfidf-svm.pkl --approach tfidf-svm --train-info results/tfidf_svm_train_info.json
      deps:
        - ${data}/processed/science_grants_tagged_title_synopsis.jsonl
        - ${grants_tagger}/train.py
      params:
        - train.tfidf-svm.tfidf.min_df
        - train.tfidf-svm.svm__estimator.class_weight
        - train.tfidf-svm.tfidf.ngram_range
      outs:
        - ${models}/tfidf-svm.pkl
      metrics:
        - ${results}/tfidf_svm_train_info.json:
            cache: false
    evaluate_tfidf_svm:
      cmd: grants_tagger evaluate model tfidf-svm ${models}/tfidf-svm.pkl ${data}/processed/science_grants_tagged_title_synopsis.jsonl
        ${models}/label_binarizer.pkl --results-path ${results}/tfidf_svm.json
      deps:
        - ${grants_tagger}/evaluate_model.py
        - ${models}/label_binarizer.pkl
        - ${models}/tfidf-svm.pkl
      metrics:
        - ${results}/tfidf_svm.json:
            cache: false
    train_scibert:
      cmd: grants_tagger train ${data}/processed/science_grants_tagged_title_synopsis.jsonl
        ${models}/label_binarizer.pkl ${models}/scibert --approach scibert --train-info ${results}/scibert_train_info.json
      deps:
        - ${data}/processed/science_grants_tagged_title_synopsis.jsonl
        - ${grants_tagger}/train.py
      params:
        - train.scibert.validation_split
        - train.scibert.learning_rate
        - train.scibert.epochs
      outs:
        - ${models}/scibert
    evaluate_scibert:
      cmd: grants_tagger evaluate model scibert ${models}/scibert ${data}/processed/science_grants_tagged_title_synopsis.jsonl
        ${models}/label_binarizer.pkl --results-path ${results}/scibert.json
      deps:
        - ${grants_tagger}/evaluate_model.py
        - ${models}/label_binarizer.pkl
        - ${models}/scibert
      metrics:
        - ${results}/scibert.json:
            cache: false
    #  train_science_ensemble:
    #    cmd: grants_tagger train ${data}/processed/science_grants_tagged_title_synopsis.jsonl
    #      ${models}/label_binarizer-2021.04.0.pkl ${models}/science_ensemble-2021.04.0 --approach science-ensemble
    #    deps:
    #    - ${data}/processed/science_grants_tagged_title_synopsis.jsonl
    #    - ${grants_tagger}/train.py
    #    params:
    #    - train.tfidf-svm.tfidf.min_df
    #    - train.tfidf-svm.svm__estimator.class_weight
    #    - train.tfidf-svm.tfidf.ngram_range
    #    - train.scibert.validation_split
    #    - train.scibert.learning_rate
    #    - train.scibert.epochs
    #    outs:
    #    - ${models}/science_ensemble-2021.04.0
    evaluate_science_ensemble:
      cmd: grants_tagger evaluate model science-ensemble ${models}/tfidf-svm.pkl,${models}/scibert
        ${data}/processed/science_grants_tagged_title_synopsis.jsonl ${models}/label_binarizer.pkl
        --results-path ${results}/science_ensemble.json
      deps:
        - ${grants_tagger}/evaluate_model.py
        - ${models}/tfidf-svm.pkl
        - ${models}/scibert
        - ${models}/label_binarizer.pkl
      #- ${models}/label_binarizer-2021.04.0.pkl
      #- ${models}/science_ensemble-2021.04.0
      metrics:
        - ${results}/science_ensemble.json:
            cache: false
