vars:
    - model_key: "Wellcome/WellcomeBertMesh"
    - data_path: "../../data/raw/allMeSH_2021.json"
    - scripts_folder: "../../scripts"
    - output_dir: "../../bertmesh_outs/pipeline"

stages:
    train:
        cmd: >-
            python ${scripts_folder}/train_bertmesh_script.py
            --model_key ${model_key}
            --data_path ${data_path}
            --output_dir ${output_dir}
            --max_samples 10
            --per_device_train_batch_size 4
            --per_device_eval_batch_size 4
        deps:
            - ${data_path}
        params:
            - ../../grants_tagger_light/training/cli_args/train_args.py:
                  - BertMeshTrainingArguments
        outs:
            - ${output_dir}/best
