name: tests
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.5"
      - name: Install dependencies
        run: |
          poetry install --only dev
      - name: Run tests
        run: |
          pytest
